
export const SET_FILTER_INPUT_TEXT = 'SET_FILTER_INPUT_TEXT';
export const SET_ALL_MEALS_LIST = 'SET_ALL_MEALS_LIST';
export const SET_IS_USER_CREATED = 'SET_IS_USER_CREATED';
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOADING_MESSAGE = "SET_LOADING_MESSAGE";
export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';





